In [33]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
df = pd.read_csv('/Users/yagyansh/ml-models-understanding/datasets/advertising.csv')

In [35]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [36]:
cols_to_use = ['TV', 'Radio', 'Newspaper']
df = df[cols_to_use]

df.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [50]:
df['Sales'] = df['TV'] + df['Radio'] + df['Newspaper']
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2  337.1
1   44.5   39.3       45.1  128.9
2   17.2   45.9       69.3  132.4
3  151.5   41.3       58.5  251.3
4  180.8   10.8       58.4  250.0

In [51]:
X = df.drop('Sales', axis=1)
y = df['Sales']

In [52]:
from sklearn.preprocessing import PolynomialFeatures

In [53]:
polynomial_converter = PolynomialFeatures(degree = 2, 
                                            interaction_only = False, 
                                            include_bias = False)

In [54]:
polynomial_converter.fit(X)

PolynomialFeatures(include_bias=False)

In [58]:
poly_features = polynomial_converter.transform(X)

In [59]:
poly_features.shape

(200, 9)

In [60]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [61]:
X.iloc[0]

TV           230.1
Radio         37.8
Newspaper     69.2
Name: 0, dtype: float64

In [64]:
230.1*230.1

52946.009999999995

In [66]:
37.8**2

1428.8399999999997

In [67]:
poly_features = polynomial_converter.fit_transform(X) 

In [68]:
poly_features.shape

(200, 9)

In [69]:
from sklearn.model_selection import train_test_split 

In [73]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.2, random_state=42)

In [71]:
X_train.shape

(160, 9)

In [72]:
X_test.shape 

(40, 9)

In [74]:
y_train.shape

(160,)

In [75]:
y_test.shape

(40,)

In [76]:
from sklearn.linear_model import LinearRegression 

In [77]:
model = LinearRegression() 

In [78]:
model.fit(X_train, y_train) 
y_pred = model.predict(X_test) 


In [80]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score 

MAE = mean_absolute_error(y_test, y_pred) 
MSE = mean_squared_error(y_test, y_pred) 
R2 = r2_score(y_test, y_pred) 

In [81]:
MAE

4.3085535139653075e-12

In [82]:
MSE

2.3359195029504776e-23

In [83]:
R2

1.0

In [85]:
model.coef_

array([ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  7.39296116e-17,
        1.98013849e-17, -1.99325403e-16,  4.27585441e-16, -4.76343908e-16,
        4.30017888e-16])

In [87]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])